config/routes.rb
TwitterApp::Application.routes.draw do

  devise_for :users, :controllers => { :registrations => "registrations" }

  root "welcome#index"

  get "tweets/update_all_tweets"
  get "welcome/index"
  get "welcome/about"

  

  resources :comments

  resources :tweets

  resources :users

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	 validates_length_of :tweets, :maximum => 350, :message => "Tweet exceeded limit of 350!"

	 belongs_to :user
	 has_many :comments
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]
  #before_filter :authenticate_user!

  include TweetsHelper

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    # get all comments for this tweet
    @comments = @tweet.comments

    # get the number of comments each tweet has
    @num_comments = @comments.count

  end

  # this method is defined to retroactively update all the num_comments !!
  # this is a throw-away method which is discarded once it's function is complete!!
  def update_all_tweets

    tweets = Tweet.all

    @response_html = ""

    tweets.each do |tweet|
      set_num_comments (tweet.id)

      @response_html += "Update tweet <b>#{tweet.id}<b><br><br> \n "

    end

  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST / tweets
  # POST / tweets.json
  # POST / tweets.js
  def create
    @tweet = Tweet.new(tweet_params)

    # This is necessary to link each tweets user_id to the current_user.id
    @tweet.user_id = current_user.id

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tweet }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  # DELETE /tweets/1.json
  def destroy
    @tweet.destroy
    respond_to do |format|
      format.html { redirect_to tweets_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:tweets, :user_id, :comment_id, :num_comments)
    end
end

app/helpers/tweets_helper.rb
module TweetsHelper

		# this will update the tweet resource to tell is how many comments each has
		def set_num_comments(posted_tweet_id)
			
			# To test that this helper method is working do
			puts "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"
			puts "DEBUG CODE"
			puts "Hey this is coming from the set_num_comments helper method" 
			puts "tweet_id being passed = #{posted_tweet_id}"
			puts "+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++"

			num_comments = Comment.where("tweet_id = #{posted_tweet_id}").count
			# select * from tweets where tweet_id = 12 (NB: where uses a key - value pair)

			puts "**********************************************"
			puts "DEBUG CODE"
			puts "Number of comments = " + num_comments.to_s
			puts "**********************************************"

			tweet = Tweet.find(posted_tweet_id)
			tweet.num_comments = num_comments
			tweet.save

			puts "***********SAVED***********"

		end

end

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="response_message1"></div>

  <div class="field">
    <%= f.label :tweets %><br>
    <%= f.text_area :tweets, size: "60x4", :placeholder => "Enter your tweets here" %>
  </div>
  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/tweets/create.js.erb
$('#response_message1').append('<h5>Your comment is: <%= @tweet.tweets %></h5>')

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<h2>Listing tweets</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Twitter handle</th> 
      <th>Tweet</th>
      <th>Num comments</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.user.twitter_name %></td>
        <td><%= tweet.tweets %></td>
        <td><%= tweet.num_comments %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Tweet', new_tweet_path, :class => "btn btn-default" %>

app/views/tweets/new.html.erb
<h3>New tweet</h3>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<blockquote>
  <h2> <%= @tweet.tweets %> </h2>
  <small><i>by&nbsp</i> <%= @tweet.user.email %></small>
</blockquote>

<% if @num_comments != 0 %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Tweet ID</th>
      <th>User ID</th>
      <th>Comment text</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.tweet_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= comment.comments %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%else%>
	<p> You don't have any comments </p>
	<%= link_to "Add a comment", new_comment_path(:tweet_id => @tweet.id), :class => "btn btn-default" %>
<%end%>

app/views/tweets/update_all_tweets.html.erb
<h3>This is updating all Tweets.  Be careful.</h3>
<br><br>
<%= @response_html %>